---
- hosts: all
  tasks:
    - name: Copy files over
      synchronize: src={{src}} dest={{dest|default('~/bitwalden-node')}} delete=yes recursive=yes rsync_opts="--exclude 'node*' --exclude '.*.swp' --exclude '.git/'"
    
    - name: Run make to ensure nodeenv is set up
      shell: make chdir=bitwalden-node creates=build/bitwalden-server-node.js

